# fly.toml app configuration file generated for samu-api on 2023-05-30T23:01:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "samu-api"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
